### ISSUE TITLE
Installation ❓

### ISSUE THREAD

**Issue by bl4nk0n** [dreamyoak/Oak-Grabber-V2#7]
4. **Send your EXE file to your victims**

Q : How to get .exe files? When i already setup, file type still on python.
![Screenshot 2024-03-30 001106](https://github.com/dreamyoak/Oak-Grabber-V2/assets/37048485/4c63534a-6b4b-422a-afb6-9c92bb70afd9)
![Screenshot 2024-03-30 001123](https://github.com/dreamyoak/Oak-Grabber-V2/assets/37048485/2dde8bc9-01c1-465e-8cdc-65a7bf0881a0)

**Comment by dreamyoak** [comment]
did u run the builder?

**Comment by bl4nk0n** [comment]
> did u run the builder?

i did, i got main.py after set up.

**Comment by dreamyoak** [comment]
its prob a problem with ur pyinstaller try uninstalling it and reinstalling again
pip uninstall pyinstaller 
pip install pyinstaller

**Comment by bl4nk0n** [comment]
it worked now.
but..
![image](https://github.com/dreamyoak/Oak-Grabber-V2/assets/37048485/a2dd62d6-fff2-4523-aa4e-5f5192277ea0)

**Comment by dreamyoak** [comment]
oak grabber old so u can use another obf
